### ISSUE TITLE
Wrong API credentials error whenever anything on the Trello board is modified.

### ISSUE THREAD

**Issue by imoore2038** [alexktzk/trello-habitica#11]
Currently, I can log in to Habitica via the Trello powerup fine, but when I attempt to move a card from one list to another or otherwise modify the board, Trello loses its connection with Habitica and displays the "Please log in again" error.

**Comment by danuid** [comment]
I made some changes, not a ideal solution, but works. You can try using my github pages at: https://danuid.github.io/trello-habitica/

**Comment by joanroig** [comment]
@danuid can you make a pull request? I think it will be useful that @alexktzk integrates this 👍

**Comment by alexktzk** [comment]
@danuid thanks for your contribution! please make a PR with your changes and I'll merge them

**Comment by danuid** [comment]
@joanroig @alexktzk Sure, the pull request is [here](https://github.com/alexktzk/trello-habitica/pull/17).

I would like to point out the root issue: when I login from a different browser, the original session will lose the Habitca token stored in Trello's "secret" API. So if I switch between two browsers, I'll have to enter the token again and again.
I have to use 'set/get' API intead of 'storeSecret/loadSecret'. This is less secure, but at least it works for me.
