### ISSUE TITLE
Unable to sync Todos from Habitica to Trello

### ISSUE THREAD

**Issue by aleks-rope** [alexktzk/trello-habitica#20]
I'm unable to fetch my Todos from Habitica in Trello. 

My current configuration for my power up is:
Im using `https://alexktzk.github.io/trello-habitica` as the iframe link.

I enabled all the capabalities:
- board-buttons
- card-badges
- card-detail-badges
- list-actions

I'm able to login just fine. However my Todos do not get imported I have attached a screenshot.

<img width="1435" alt="Screen Shot 2020-05-16 at 3 31 28" src="https://user-images.githubusercontent.com/58922379/82084577-72df2700-9726-11ea-8f32-271079faa2e5.png">

**Comment by alexktzk** [comment]
@aleks-rope Sorry for the late response. Probably no longer relevant, but still... I believe you're missed this step:

> 5. To start the sync process, open any list menu (three dots) and select either "Mark list as Doing" or "Mark list as Done."
