### ISSUE TITLE
how to link to habitica account?

### ISSUE THREAD

**Issue by red8top** [alexktzk/trello-habitica#3]
I feel like I missed something really obvious - I forked my own version, set up Trello, but how do I link it to my Habitica account?

**Comment by alexktzk** [comment]
Sorry for the late answer.
Add power-up to your board and the login button should appear. Then authorize with your client id and api token from Habitica. They can be found in the settings under the API section.

**Comment by red8top** [comment]
Thanks for the response!  But I don't get a login button upon adding the power-up, could I have missed...something?
![image](https://user-images.githubusercontent.com/1339974/58103545-2b749800-7bb1-11e9-9e14-6f055ebb4719.png)

**Comment by alexktzk** [comment]
@red8top Can you please check the url you providing to this form as "Iframe connector url"? 
![power-up](https://user-images.githubusercontent.com/8523385/58104413-6dbbca80-7bed-11e9-8c4a-91cc25a99802.png)

I suppose your url is https://red8top.github.io/trello-habitica, but It looks like your power-up isn't published at Github Pages. In the [settings](https://github.com/red8top/trello-habitica/settings) of your repo scroll down and in the Github Pages section as a source choose **gh-pages branch**. Hope this helps!

**Comment by red8top** [comment]
You're right but I do have that option selected, but the message shows "page ready to be published" - I'll see what else I'm missing to publish and let you know, thanks for the tip!
