### ISSUE TITLE
I presume this doesn't work from the Trello mobile (android) client?

### ISSUE THREAD

**Issue by Dombo** [alexktzk/trello-habitica#4]
Given how the project is structured. 

Is it possible to do so? I'd be happy to do the research and make the changes if you suggest it is and are open to contributions.

**Comment by alexktzk** [comment]
@Dombo Any contributions to the project are much appreciated, thanks for offering! But unfortunately, I think we don't have that flexibility with mobile clients for now. We can only choose from a few official Power-ups written by the Trello team.

But it works from a web browser on mobile. Just in case.
