### ISSUE TITLE
Habitica stats info

### ISSUE THREAD

**Issue by ofekmiz** [alexktzk/trello-habitica#6]
I had an idea to add the Habitca's hp ,exp & gold to Trello's header:
![image](https://user-images.githubusercontent.com/39601942/58399663-8f8bd600-8061-11e9-8e38-08d81812340f.png)

I already implemented it on my user using cjs chrome plugin, If you like it I can send a pull request. 
(I never did a pull request to another project before, some guidance would be appreciated 😊).

**Comment by alexktzk** [comment]
@ofekmiz I’ve seen your solution and even tried to add it to the project but problem is that it modifies DOM directly but not through the methods provided for Power-Ups. 

We can use icons for board buttons so maybe a better solution would be to make 3 of them for every stats. Also they would look more Trello way.

**Comment by ofekmiz** [comment]
Thanks for replying. 
And thanks for this awesome power-up by the way.
Good to know that modifying the DOM is impossible for Trello Power-ups, Adding board buttons sounds like a good solution. 

The main reason I think its a necessary feature is because checking tasks in trello doesn't give you that good feeling you get in Habitica when you check a task. In the Habitica site you can see the gold and exp you earned for the task instantly in a pop up message and cool sounds, that for some reason is really motivating.

Maybe instead of showing the stats we can just add popup message with the gold and exp earn for the task (there is a message like this in butler powerup for example).

**Comment by alexktzk** [comment]
@ofekmiz Thanks for your interest and ideas!

I wouldn’t say it’s not impossible but rather not preferred way. I just don’t think that Trello will accept this solution if we someday decide to submit this power-up to make it publicly accessible.

I agree with you, gamified part of Habitica is important and must be transfered to the power-up as well. I tried to add its basic implementation.

![Screen Shot 2019-05-29 at 22 00 16](https://user-images.githubusercontent.com/8523385/58583693-42745380-825d-11e9-9886-fed58f2f9acd.png)

![Screen Shot 2019-05-29 at 21 54 22](https://user-images.githubusercontent.com/8523385/58583400-9599d680-825c-11e9-88b3-e9102290f06f.png)

![Screen Shot 2019-05-29 at 21 54 47](https://user-images.githubusercontent.com/8523385/58583404-9894c700-825c-11e9-9f96-2b913d9044f6.png)

How it looks? Health points and mana points are not that important as exp and gold so I think this will be enough for now.

**Comment by ofekmiz** [comment]
Perfect!
How did you manage to add the max exp? I couldn't find it in the API

**Comment by alexktzk** [comment]
It just right there in stats, named "toNextLevel" :)

**Comment by ofekmiz** [comment]
Is this live? :)
Should I reinstall the powerup? or it should update automatically when the feature is added?

**Comment by alexktzk** [comment]
@ofekmiz It is live now :) No, just check your Trello board.

**Comment by ofekmiz** [comment]
@alexktzk  Thanks :) but it doesn't seem to work for me 😕 :
![image](https://user-images.githubusercontent.com/39601942/59162842-ab32ba00-8b00-11e9-9f97-6bc98d69077c.png)

**Comment by alexktzk** [comment]
@ofekmiz just move any card between done/doing lists to receive initial data

**Comment by ofekmiz** [comment]
@alexktzk Yea, I just figured it out :) looks great!

**Comment by alexktzk** [comment]
@ofekmiz yeah, nice suggestion you’ve made :) it looks more like Habitica now
