### ISSUE TITLE
Suggestion: Show task difficulty on card

### ISSUE THREAD

**Issue by ofekmiz** [alexktzk/trello-habitica#8]
Another suggestion :)
For example a Medium task:
![M Task](https://user-images.githubusercontent.com/39601942/58585075-65543700-8260-11e9-9f63-98dcb7a39600.png)

**Comment by alexktzk** [comment]
I suppose first letters of the words will not be that useful... Difficulty levels like T,E,M,H are hard to understand, every time you need to think what they actually stand for. I mean it's not clear that T is easier than E and H is harder than M. I hope you agree.

I wanted to solve this with color badges but maybe some users use badges for other purposes so it would be too complex to handle all possible cases. 

I like your solution but it must be something like 1,2,3,4 or A,B,C,D. Something already familiar for our eyes. Four different colors for habitica logo can be a solution. Logo actually does nothing right now, just a purple thing there.

**Comment by ofekmiz** [comment]
Colors are always a problem, I'm color-blind myself, for example ;)
What about something like this?
![image](https://user-images.githubusercontent.com/39601942/58589895-a0a83300-826b-11e9-81ec-9c6e004f8af0.png)

Like in habitica:
![image](https://user-images.githubusercontent.com/39601942/58589584-e7e1f400-826a-11e9-918d-b27352cb19fb.png)

or this?
![image](https://user-images.githubusercontent.com/39601942/58590113-098fab00-826c-11e9-8f01-0f033ba2805c.png)

or maybe with colors and number?
![image](https://user-images.githubusercontent.com/39601942/58590481-d7327d80-826c-11e9-9863-53cf40a3a1d9.png)

**Comment by alexktzk** [comment]
@ofekmiz wow! The first one looks perfect, we don't even need a logo anymore.

**Comment by ofekmiz** [comment]
It looks awesome! thanks!
