### ISSUE TITLE
Possible typo in setup

### ISSUE THREAD

**Issue by sguthrie** [alexktzk/trello-habitica#9]
callback isn't an option in Trello as of 06/2019. Perhaps this is a typo for card-back?

**Comment by alexktzk** [comment]
@sguthrie please share some more details.
what steps do you perform? file name and line number where error occurred?

**Comment by sguthrie** [comment]
This is purely a documentation issue:

README.md

> To work properly this Power-Up requires some permissions. Make sure you've checked all of the following:
> - board-buttons
> - callback
> - card-badges
> - card-buttons

Perhaps this is meant to be:
> To work properly this Power-Up requires some permissions. Make sure you've checked all of the following:
> - board-buttons
> - _card-back_
> - card-badges
> - card-buttons

**Comment by alexktzk** [comment]
Sorry, I misunderstood you. Yes, Trello must have made changes. Current proper permissions are:

- board-buttons
- card-badges
- card-detail-badges
- list-actions

Thanks for pointhing out!
